name: blueprint-guard

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify blueprint files exist
        run: |
          test -f "00_Policy/Systems_Integration_Blueprint.md" || { echo "Missing Systems_Integration_Blueprint.md"; exit 1; }
          test -f "00_Policy/Systems_Integration_Blueprint.png" || { echo "Missing Systems_Integration_Blueprint.png"; exit 1; }
      - name: Check freshness (30 days or since last tag)
        shell: bash
        run: |
          set -euo pipefail
          FILES=("00_Policy/Systems_Integration_Blueprint.md" "00_Policy/Systems_Integration_Blueprint.png")

          # Get date of last tag if any
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            echo "Last tag: $LAST_TAG"
            REF="$LAST_TAG"
          else
            REF="HEAD~1"
          fi

          # Fail if no changes to blueprint files since REF and older than 30 days
          NOW=$(date +%s)
          STALE=0
          for f in "${FILES[@]}"; do
            if git log -1 --format=%ct -- "$f" >/tmp/ts; then
              TS=$(cat /tmp/ts)
              AGE_DAYS=$(( (NOW - TS) / 86400 ))
              echo "$f last updated $AGE_DAYS day(s) ago"
              if [ $AGE_DAYS -gt 30 ]; then
                STALE=1
              fi
            else
              echo "No history for $f — marking as stale"
              STALE=1
            fi
          done

          if [ $STALE -eq 1 ]; then
            echo "::error::Systems Integration Blueprint is stale (>30 days) or not updated since last release."
            exit 1
          fi

      - name: Summary
        run: |
          echo "Blueprint guard passed." >> $GITHUB_STEP_SUMMARY